mongo:
  image: mongo:3.0.4
  ports:
    - "27017:27017"
  command: --smallfiles --rest
rabbitmq:
  image: rabbit
  ports:
    - "61613:61613"
    - "15672:15672"
  environment:
    - RABBITMQ_USER=root
    - RABBITMQ_PASS=123456
web:
  build: ./
  volumes:
    - "./:/src"
  extra_hosts:
    - "hostmachine:192.168.102.104"
  ports:
    - "80:3000"
  links:
   - mongo
   - rabbitmq
